name: hl7fwa-model
channels:
  - defaults
dependencies:
  - python=3.6
  - numpy=1.14.3
  - pandas=0.22.0
  - scikit-learn=0.19.1
  - pip:
    - mlflow==1.0.0
    - cloudpickle
    - azure-storage==0.36.0
    - pyarrow==0.14.1