kind: ModelTraining
id: reuters-classifier-id
spec:
  model:
    name: reuters-classifier
    version: 1.0
  toolchain: mlflow  # MLFlow training toolchain integration
  entrypoint: main
  workDir: mlflow/tensorflow/reuters_classifier # MLproject location (in GitHub)
  hyperParameters:
    maxwords: "999"
  data:
    - connName: models-output
      localPath: mlflow/tensorflow/reuters_classifier/data/
      remotePath: /reuters/
  resources:
    limits:
      cpu: 4
      memory: 2Gi
    requests:
      cpu: 4
      memory: 2Gi
  vcsName: reuters-classifier-repo