kind: ModelTraining
id: reuters-classifier
spec:
  model:
    name: reuters-classifier
    version: 1.0
  toolchain: mlflow  # MLFlow training toolchain integration
  entrypoint: main
  workDir: mlflow/tensorflow/reuters_classifier # MLproject location (in GitHub)
  dataNotRequired: true
  hyperParameters:
    maxwords: "999"
  resources:
    limits:
      cpu: 3
      memory: 2Gi
    requests:
      cpu: 3
      memory: 2Gi
  algorithmSource:
    vcs:
      connection: odahu-flow-examples
