language: python
dist: bionic
python: 3.6
sudo: true
services:
  - docker
install: skip
jobs:
  include:
    - stage: security
      before_script:
        - sudo make install-vulnerabilities-checker
      script:
        - make check-vulnerabilities
