name: flower_classifier
channels:
  - defaults
  - anaconda
dependencies:
  - python=3.7
  - pandas=1.0.1
  - scikit-learn=0.22.1
  - tensorflow-gpu=1.15.0
  - keras=2.2.4
  - pip:
    - mlflow==1.5.0
    - pillow==7.0.0
