name: flower_classifier
channels:
  - defaults
  - anaconda
dependencies:
  - pip
  - python=3.6.9
  - pandas=1.0.1
  - scikit-learn=0.22.1
  - tensorflow-gpu=1.13.1
  - keras=2.2.4
  - h5py<3.0.0
  - pip:
    - mlflow==1.5.0
    - pillow==7.0.0
