kind: ModelTraining
id: wine
spec:
  model:
    name: wine
    version: 1.0
  toolchain: mlflow-project
  entrypoint: main
  workDir: mlflow/sklearn-triton/wine
  data:
    - connection: wine
      localPath: mlflow/sklearn/wine/wine-quality.csv
  hyperParameters:
    alpha: "1.0"
  resources:
    limits:
      cpu: 4
      memory: 4Gi
    requests:
      cpu: 2
      memory: 2Gi
  algorithmSource:
    vcs:
      connection: odahu-flow-examples

