kind: ModelTraining
id: flower-classifier
spec:
  model:
    name: flower_classifier
    version: 3.0
  toolchain: mlflow
  entrypoint: main
  workDir: mlflow/tensorflow/flower_classifier
  resources:
    limits:
      cpu: 4024m
      memory: 4024Mi
    requests:
      cpu: 4024m
      memory: 4024Mi
  vcsName: odahuflow-examples
  
