name: dog_cats
channels:
  - defaults
dependencies:
  - pip
  - python=3.7
  - pandas=1.1.3
  - numpy=1.19.2
  - tensorflow-gpu=2.4.1
  - tensorflow=2.4.1
  - keras=2.4.3
  - pip:
      - mlflow==1.13.1
      - pillow==8.2.0
