kind: ModelTraining
id: tensorflow
spec:
  model:
    name: tensorflow
    version: 2.0
  toolchain: mlflow
  entrypoint: main
  workDir: mlflow/tensorflow/example
  resources:
    limits:
      cpu: 4024m
      memory: 4024Mi
    requests:
      cpu: 2024m
      memory: 2024Mi
  vcsName: legion-examples
  
