kind: ModelTraining
id: flower-classifier
spec:
  model:
    name: flower-classifier
    version: 2.0
  toolchain: mlflow
  entrypoint: main
  workDir: mlflow/tensorflow/flower_classifier
  dataNotRequired: true
  resources:
    limits:
      gpu: 1
      cpu: 4
      memory: 16Gi
    requests:
      gpu: 1
      cpu: 4
      memory: 16Gi
  algorithmSource:
    vcs:
      connection: odahu-flow-examples
