kind: ModelTraining
id: flower-classifier
spec:
  model:
    name: flower-classifier
    version: 2.0
  toolchain: mlflow-gpu
  entrypoint: main
  workDir: mlflow/tensorflow/flower_classifier
  resources:
    limits:
      gpu: 1
      cpu: 4
      memory: 16Gi
    requests:
      gpu: 1
      cpu: 4
      memory: 16Gi
  algorithmSource:
    algorithmSource:
      vcs:
        connName: odahu-flow-examples
