kind: ModelTraining
id: flower-classifier
spec:
  model:
    name: flower-classifier
    version: 2.0
  toolchain: mlflow
  entrypoint: main
  workDir: mlflow/tensorflow/flower_classifier
  resources:
    limits:
      gpu: 2
      cpu: 4
      memory: 16Gi
    requests:
      gpu: 2
      cpu: 4
      memory: 16Gi
  vcsName: odahu-flow-examples