kind: ModelTraining
id: airflow-wine
spec:
  model:
    name: wine
    version: 1.0
  toolchain: mlflow
  entrypoint: main
  workDir: mlflow/sklearn/wine
  data:
    - connName: wine
      localPath: mlflow/sklearn/wine/wine-quality.csv
  hyperParameters:
    alpha: "1.0"
  resources:
    limits:
      cpu: 4
      memory: 4Gi
    requests:
      cpu: 4
      memory: 4Gi
  vcsName: odahu-flow-examples

